# Generated by Django 6.0.3 on 2026-04-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='emergency_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('sos', 'SOS')], default='manual', max_length=20),
        ),
    ]
