# Generated by Django 6.0.3 on 2026-04-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('en_route', 'En Route'), ('offline', 'Offline')], default='available', max_length=20),
        ),
    ]
